CONFIG_GPIO=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL=y

# Enable Ultrasonic ranger
CONFIG_SENSOR=y
CONFIG_HC_SR04=y

# Enable printing floats
CONFIG_CBPRINTF_FP_SUPPORT=y 